# Generated by Django 5.1.2 on 2025-12-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('platform', models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('pinterest', 'Pinterest'), ('tiktok', 'TikTok'), ('snapchat', 'Snapchat'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('github', 'GitHub'), ('behance', 'Behance'), ('dribbble', 'Dribbble'), ('medium', 'Medium'), ('reddit', 'Reddit'), ('other', 'Other')], help_text='Social media platform', max_length=50, null=True)),
                ('url', models.URLField(blank=True, help_text='Social media profile URL', null=True)),
                ('icon', models.FileField(blank=True, help_text='Icon file for the social media platform', null=True, upload_to='social_media_icons/')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Show this social media link on website', null=True)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes', null=True)),
            ],
            options={
                'verbose_name_plural': 'Social Media',
                'ordering': ['platform'],
                'indexes': [models.Index(fields=['platform'], name='socialmedia_platfor_bd00f0_idx'), models.Index(fields=['is_active'], name='socialmedia_is_acti_6bf7ca_idx')],
            },
        ),
    ]
