# Generated by Django 5.1.2 on 2025-12-14 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.FileField(blank=True, help_text='Category icon', null=True, upload_to='service_category_icons/')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('short_title', models.CharField(blank=True, help_text='Short title or secondary heading', max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('short_description', models.TextField(blank=True, help_text='Brief service description', max_length=1000, null=True)),
                ('description', models.TextField(blank=True, help_text='Full service description', null=True)),
                ('features', models.TextField(blank=True, help_text='Key features of the service', null=True)),
                ('benefits', models.TextField(blank=True, help_text='Benefits of using this service', null=True)),
                ('banner_image', models.ImageField(blank=True, help_text='Banner image for desktop/wide screens', null=True, upload_to='service_images/banner/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Mobile optimized image for small screens', null=True, upload_to='service_images/mobile/')),
                ('icon', models.FileField(blank=True, help_text='Service icon', null=True, upload_to='service_icons/')),
                ('price_starting_from', models.DecimalField(blank=True, decimal_places=2, help_text='Starting price', max_digits=10, null=True)),
                ('price_currency', models.CharField(blank=True, default='USD', help_text='Currency code', max_length=10, null=True)),
                ('price_period', models.CharField(blank=True, default='one_time', help_text='one_time, monthly, yearly, hourly', max_length=20, null=True)),
                ('is_free', models.BooleanField(blank=True, default=False, help_text='Is this a free service?', null=True)),
                ('has_custom_pricing', models.BooleanField(blank=True, default=False, help_text='Custom pricing available', null=True)),
                ('duration', models.CharField(blank=True, help_text="Service duration (e.g., '2 weeks', '1 month')", max_length=100, null=True)),
                ('delivery_time', models.CharField(blank=True, help_text='Expected delivery time', max_length=100, null=True)),
                ('service_type', models.CharField(blank=True, help_text="Type of service (e.g., 'Consultation', 'Implementation')", max_length=100, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=300, null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, null=True)),
                ('is_featured', models.BooleanField(blank=True, default=False, null=True)),
                ('is_pinned', models.BooleanField(blank=True, default=False, null=True)),
                ('is_popular', models.BooleanField(blank=True, default=False, help_text='Mark as popular service', null=True)),
                ('views_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('inquiries_count', models.PositiveIntegerField(blank=True, default=0, help_text='Number of service inquiries', null=True)),
                ('likes_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory')),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('inquiry_type', models.CharField(blank=True, choices=[('quote', 'Request Quote'), ('consultation', 'Free Consultation'), ('demo', 'Request Demo'), ('information', 'General Information'), ('custom', 'Custom Request')], default='information', max_length=20, null=True)),
                ('lead_source', models.CharField(blank=True, choices=[('website', 'Website Contact Form'), ('service_page', 'Service Page'), ('phone', 'Phone Call'), ('email', 'Direct Email'), ('referral', 'Referral'), ('social_media', 'Social Media'), ('other', 'Other')], default='website', max_length=20, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, help_text='Inquiry message or requirements', null=True)),
                ('budget_range', models.CharField(blank=True, help_text='Budget range if applicable', max_length=100, null=True)),
                ('timeline', models.CharField(blank=True, help_text='Project timeline if applicable', max_length=100, null=True)),
                ('is_contacted', models.BooleanField(blank=True, default=False, null=True)),
                ('is_converted', models.BooleanField(blank=True, default=False, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the lead', null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_term', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_content', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='services.service')),
            ],
            options={
                'verbose_name_plural': 'Service Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['-created_at'], name='services_se_created_d8afb6_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status'], name='services_se_status_288ecc_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['slug'], name='services_se_slug_4657d0_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category'], name='services_se_categor_7ca2f8_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelead',
            index=models.Index(fields=['-created_at'], name='services_se_created_85b77b_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelead',
            index=models.Index(fields=['is_contacted'], name='services_se_is_cont_e1b30d_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelead',
            index=models.Index(fields=['is_converted'], name='services_se_is_conv_ed3d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='servicelead',
            index=models.Index(fields=['service'], name='services_se_service_b7118b_idx'),
        ),
    ]
