# Generated by Django 5.1.2 on 2025-12-14 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('short_title', models.CharField(blank=True, help_text='Short title or secondary heading for the blog post', max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('short_description', models.TextField(blank=True, help_text='Extended description or summary of the blog post', max_length=1000, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('banner_image', models.ImageField(blank=True, help_text='Banner image for desktop/wide screens', null=True, upload_to='blog_images/banner/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Mobile optimized image for small screens', null=True, upload_to='blog_images/mobile/')),
                ('estimated_time', models.PositiveIntegerField(blank=True, help_text='Estimated reading time in minutes', null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=300, null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, null=True)),
                ('is_featured', models.BooleanField(blank=True, default=False, null=True)),
                ('is_pinned', models.BooleanField(blank=True, default=False, null=True)),
                ('views_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('likes_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('shares_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='blogs', to='blog.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_source', models.CharField(blank=True, choices=[('newsletter', 'Newsletter Signup'), ('download', 'Resource Download'), ('contact', 'Contact Form'), ('demo', 'Demo Request'), ('other', 'Other')], default='other', max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_contacted', models.BooleanField(blank=True, default=False, null=True)),
                ('is_converted', models.BooleanField(blank=True, default=False, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the lead', null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_refcode', models.CharField(blank=True, max_length=100, null=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='blog.blog')),
            ],
            options={
                'verbose_name_plural': 'Blog Leads',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='blog_blogle_created_398d67_idx'), models.Index(fields=['is_contacted'], name='blog_blogle_is_cont_e1304b_idx'), models.Index(fields=['is_converted'], name='blog_blogle_is_conv_9fd5cb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['-created_at'], name='blog_blog_created_602a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['status'], name='blog_blog_status_e6780b_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['slug'], name='blog_blog_slug_d925e3_idx'),
        ),
    ]
