# Generated by Django 6.0 on 2025-12-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('field_name', models.CharField(help_text='The field label (e.g., Email, Mobile No)', max_length=100)),
                ('placeholder', models.CharField(blank=True, help_text='The placeholder text for this field', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this field is active or not')),
            ],
            options={
                'verbose_name': 'Blog Dynamic Field',
                'verbose_name_plural': 'Blog Dynamic Fields',
            },
        ),
        migrations.AlterModelOptions(
            name='blogleads',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='blogleads',
            name='blog_blogle_created_398d67_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogleads',
            name='blog_blogle_is_cont_e1304b_idx',
        ),
        migrations.RemoveIndex(
            model_name='blogleads',
            name='blog_blogle_is_conv_9fd5cb_idx',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='mobile_image',
        ),
        migrations.AddField(
            model_name='blog',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Logo image (Recommended: 250x250)', null=True, upload_to='blog_images/mobile/'),
        ),
        migrations.AddField(
            model_name='blog',
            name='lp_image',
            field=models.ImageField(blank=True, help_text='Landing page image (Recommended: 600x600)', null=True, upload_to='casestudy_images/lp/'),
        ),
        migrations.AddField(
            model_name='blogleads',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores dynamic lead data like name, email, mobile etc'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Banner image for desktop/wide screens (Recommended: 300x400)', null=True, upload_to='blog_images/banner/'),
        ),
        migrations.AlterField(
            model_name='blogleads',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='blog.blog'),
        ),
        migrations.AddField(
            model_name='blogdynamicfield',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_fields', to='blog.blog'),
        ),
        migrations.RemoveField(
            model_name='blogleads',
            name='company',
        ),
        migrations.RemoveField(
            model_name='blogleads',
            name='email',
        ),
        migrations.RemoveField(
            model_name='blogleads',
            name='is_contacted',
        ),
        migrations.RemoveField(
            model_name='blogleads',
            name='is_converted',
        ),
        migrations.RemoveField(
            model_name='blogleads',
            name='lead_source',
        ),
        migrations.RemoveField(
            model_name='blogleads',
            name='message',
        ),
        migrations.RemoveField(
            model_name='blogleads',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blogleads',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='blogleads',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='blogleads',
            name='utm_campaign',
        ),
        migrations.RemoveField(
            model_name='blogleads',
            name='utm_medium',
        ),
        migrations.RemoveField(
            model_name='blogleads',
            name='utm_refcode',
        ),
        migrations.RemoveField(
            model_name='blogleads',
            name='utm_source',
        ),
    ]
