# Generated by Django 6.0 on 2025-12-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogdynamicfield_alter_blogleads_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdynamicfield',
            name='sequence',
            field=models.IntegerField(default=1, help_text='Order of the field in the case study form'),
        ),
    ]
