# Generated by Django 5.1.2 on 2025-12-14 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Case Study Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('short_title', models.CharField(blank=True, help_text='Short title or secondary heading for the case study', max_length=300, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('short_description', models.TextField(blank=True, help_text='Extended description or summary of the case study', max_length=1000, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('banner_image', models.ImageField(blank=True, help_text='Banner image for desktop/wide screens', null=True, upload_to='casestudy_images/banner/')),
                ('mobile_image', models.ImageField(blank=True, help_text='Mobile optimized image for small screens', null=True, upload_to='casestudy_images/mobile/')),
                ('estimated_time', models.PositiveIntegerField(blank=True, help_text='Estimated reading time in minutes', null=True)),
                ('client_name', models.CharField(blank=True, help_text='Client or company name', max_length=200, null=True)),
                ('client_industry', models.CharField(blank=True, help_text='Industry sector', max_length=100, null=True)),
                ('project_duration', models.CharField(blank=True, help_text="Project duration (e.g., '3 months', '6 weeks')", max_length=100, null=True)),
                ('project_budget', models.CharField(blank=True, help_text='Project budget range', max_length=100, null=True)),
                ('results_summary', models.TextField(blank=True, help_text='Key results and outcomes', max_length=500, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=300, null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20, null=True)),
                ('is_featured', models.BooleanField(blank=True, default=False, null=True)),
                ('is_pinned', models.BooleanField(blank=True, default=False, null=True)),
                ('views_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('likes_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('shares_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('downloads_count', models.PositiveIntegerField(blank=True, default=0, help_text='Number of times case study was downloaded', null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_study_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='casestudy.casestudycategory')),
            ],
            options={
                'verbose_name_plural': 'Case Studies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudyLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, help_text='Job title or position', max_length=100, null=True)),
                ('lead_source', models.CharField(blank=True, choices=[('download', 'Case Study Download'), ('contact', 'Contact Form'), ('demo', 'Demo Request'), ('consultation', 'Free Consultation'), ('newsletter', 'Newsletter Signup'), ('other', 'Other')], default='other', max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_contacted', models.BooleanField(blank=True, default=False, null=True)),
                ('is_converted', models.BooleanField(blank=True, default=False, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the lead', null=True)),
                ('utm_source', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_medium', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_campaign', models.CharField(blank=True, max_length=100, null=True)),
                ('utm_refcode', models.CharField(blank=True, max_length=100, null=True)),
                ('case_study', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='casestudy.casestudy')),
            ],
            options={
                'verbose_name_plural': 'Case Study Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['-created_at'], name='casestudy_c_created_5a8a94_idx'),
        ),
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['status'], name='casestudy_c_status_8a8a25_idx'),
        ),
        migrations.AddIndex(
            model_name='casestudy',
            index=models.Index(fields=['slug'], name='casestudy_c_slug_421584_idx'),
        ),
        migrations.AddIndex(
            model_name='casestudylead',
            index=models.Index(fields=['-created_at'], name='casestudy_c_created_195aea_idx'),
        ),
        migrations.AddIndex(
            model_name='casestudylead',
            index=models.Index(fields=['is_contacted'], name='casestudy_c_is_cont_35644d_idx'),
        ),
        migrations.AddIndex(
            model_name='casestudylead',
            index=models.Index(fields=['is_converted'], name='casestudy_c_is_conv_b730f5_idx'),
        ),
    ]
