# Generated by Django 6.0 on 2025-12-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0002_casestudytag_casestudy_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudyDynamicField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('field_name', models.CharField(help_text='The field label (e.g., Email, Mobile No)', max_length=100)),
                ('placeholder', models.CharField(blank=True, help_text='The placeholder text for this field', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this field is active or not')),
            ],
            options={
                'verbose_name': 'Case Study Dynamic Field',
                'verbose_name_plural': 'Case Study Dynamic Fields',
            },
        ),
        migrations.AlterModelOptions(
            name='casestudylead',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='casestudylead',
            name='casestudy_c_created_195aea_idx',
        ),
        migrations.RemoveIndex(
            model_name='casestudylead',
            name='casestudy_c_is_cont_35644d_idx',
        ),
        migrations.RemoveIndex(
            model_name='casestudylead',
            name='casestudy_c_is_conv_b730f5_idx',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='mobile_image',
        ),
        migrations.RemoveField(
            model_name='casestudy',
            name='short_title',
        ),
        migrations.AddField(
            model_name='casestudy',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Logo image (Recommended: 250x250)', null=True, upload_to='casestudy_images/mobile/'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='lp_image',
            field=models.ImageField(blank=True, help_text='Landing page image (Recommended: 600x600)', null=True, upload_to='casestudy_images/lp/'),
        ),
        migrations.AddField(
            model_name='casestudylead',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores dynamic lead data like name, email, mobile etc'),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Banner image for desktop/wide screens (Recommended: 300x400)', null=True, upload_to='casestudy_images/banner/'),
        ),
        migrations.AlterField(
            model_name='casestudylead',
            name='case_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='casestudy.casestudy'),
        ),
        migrations.AddField(
            model_name='casestudydynamicfield',
            name='case_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_fields', to='casestudy.casestudy'),
        ),
        migrations.RemoveField(
            model_name='casestudylead',
            name='company',
        ),
        migrations.RemoveField(
            model_name='casestudylead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='casestudylead',
            name='is_contacted',
        ),
        migrations.RemoveField(
            model_name='casestudylead',
            name='is_converted',
        ),
        migrations.RemoveField(
            model_name='casestudylead',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='casestudylead',
            name='lead_source',
        ),
        migrations.RemoveField(
            model_name='casestudylead',
            name='message',
        ),
        migrations.RemoveField(
            model_name='casestudylead',
            name='name',
        ),
        migrations.RemoveField(
            model_name='casestudylead',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='casestudylead',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='casestudylead',
            name='utm_campaign',
        ),
        migrations.RemoveField(
            model_name='casestudylead',
            name='utm_medium',
        ),
        migrations.RemoveField(
            model_name='casestudylead',
            name='utm_refcode',
        ),
        migrations.RemoveField(
            model_name='casestudylead',
            name='utm_source',
        ),
    ]
