# Generated by Django 6.0 on 2026-01-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casestudy', '0004_casestudydynamicfield_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='downloadable_file',
            field=models.FileField(blank=True, help_text='Upload case study file (PDF, DOCX, PPT, etc.)', null=True, upload_to='casestudy_files/'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='external_link',
            field=models.CharField(blank=True, help_text='External or landing page link for the case study', max_length=500, null=True),
        ),
    ]
