# Generated by Django 6.0 on 2025-12-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(default='Privacy Policy', max_length=255)),
                ('content', models.TextField(help_text='HTML or plain text privacy policy content')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(help_text='Policy version e.g. v1.0, v2.1', max_length=50)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policies',
                'ordering': ['-published_at'],
            },
        ),
    ]
